### ISSUE TITLE
Minimize the uneeded configuration properties

### ISSUE THREAD

**Issue by ProbablePrime** [Resonite-Community-Projects/resonite-pterodactyl#9]
I noticed that the final output of Pterodactyl includes a bunch of unneeded properties.

Anything in config.json whose end result is null, "" or [], or even {}, should be omitted from the final configuration, this makes bug hunting easier and keeps the cognitive load when reading instances low.

Could this be re-worked to exclude the unneeded parameters?

**Comment by ProbablePrime** [comment]
In particular, the adult session related matters should also be omitted. 

- https://github.com/Resonite-Community-Projects/resonite-pterodactyl/blob/master/Config.json#L5
- https://github.com/Resonite-Community-Projects/resonite-pterodactyl/blob/master/Config.json#L5
I'll do that for you in a PR.

**Comment by ProbablePrime** [comment]
https://github.com/Resonite-Community-Projects/resonite-pterodactyl/pull/10

**Comment by GrayBoltWolf** [comment]
Removed some unreferenced parameters from the default template.

Note the remaining items may be null in the template, however are referenced in[ the egg configuration.](https://github.com/Resonite-Community-Projects/resonite-pterodactyl/blob/master/egg-single-session-template.json)

**Comment by GrayBoltWolf** [comment]
[Updated](https://github.com/Resonite-Community-Projects/resonite-pterodactyl/commit/c20b0250d62575c321774c124360c041c04f732e)

**Comment by GrayBoltWolf** [comment]
[Updated](https://github.com/Resonite-Community-Projects/resonite-pterodactyl/commit/c20b0250d62575c321774c124360c041c04f732e)
